[package]
name = "rs-simple-tic-tac-toe"
version = "0.1.0"
authors = ["Marco Tan <marco.tan.200405@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
